include: linter_rules.yaml

analyzer:
  errors:
    close_sinks: warning
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: error

  language:
    strict-casts: true
    strict-inference: true
