builders:
  sampleCatalogBuilder:
    import: "package:arcgis_maps_sdk_flutter_samples/builder.dart"
    builder_factories: ["sampleCatalogBuilder"]
    build_extensions: {"$package$": ["assets/generated_samples_list.json"]}
    build_to: source
    auto_apply: root_package
